name: "my joke action"

description: "use an exernal API to retreive and display a joke"

outputs:
  joke-output:
    description: The resulting joke from the icanhazdadjokes API

runs:
  using: "node16"
  main: "main.js"